variable "name" {}
variable "location" {}
variable "vnetcidr" {}
variable "websubnetcidr" {}
variable "appsubnetcidr" {}
variable "dbsubnetcidr" {}
variable "mssql_server_admin" {}
variable "mssql_server_password" {}
variable "mssql_server_version" {}